"""Evidence and sensitivity panels for the Streamlit app.

Kept separate from streamlit_app.py so the reading of reports/ can be unit-tested
without spinning up Streamlit.
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd

from src.config import REPORTS_DIR
from src.models.coupling import usable_energy_wh

PROVENANCE_BADGE = {
    "REAL": ("✅", "measured on real logged vehicle data"),
    "SYNTHETIC": ("⚠️", "generated by our own code — proves the pipeline runs, not accuracy"),
    "COUPLED-SIM": ("🔶", "real inputs, SIMULATED coupling — a propagation study, "
                          "NOT end-to-end validation"),
}


def list_experiments(reports_dir: Path = REPORTS_DIR) -> pd.DataFrame:
    """Every experiment that has written a manifest, with its provenance."""
    rows = []
    for man in sorted(Path(reports_dir).glob("*/MANIFEST.json")):
        try:
            m = json.loads(man.read_text())
        except (json.JSONDecodeError, OSError):
            continue
        rows.append(dict(
            experiment=m.get("experiment", man.parent.name),
            provenance=m.get("provenance", "?"),
            conclusion=m.get("conclusion_type", "?"),
            protocol=m.get("split_protocol", ""),
            n=m.get("n", ""),
            seeds=len(m.get("seeds", [])),
            git=m.get("git_revision", ""),
            path=str(man.parent),
        ))
    return pd.DataFrame(rows)


def load_summary(exp_id: str, reports_dir: Path = REPORTS_DIR) -> pd.DataFrame | None:
    f = Path(reports_dir) / exp_id / "metrics_summary.csv"
    return pd.read_csv(f) if f.exists() else None


def load_findings(exp_id: str, reports_dir: Path = REPORTS_DIR) -> str | None:
    f = Path(reports_dir) / exp_id / "FINDINGS.md"
    return f.read_text() if f.exists() else None


def soh_sensitivity_curve(vehicle, consumption_wh_km: float, soc_pct: float,
                          temp_c: float, soh_values=None) -> pd.DataFrame:
    """Range against SoH, and the local km-per-percentage-point slope.

    The slope is the quantity E6 reports: because range is proportional to SoH, a
    one-point SoH error costs a fixed fraction of range, so the curve is a straight
    line whose gradient scales with state of charge.
    """
    soh_values = np.linspace(0.70, 1.00, 31) if soh_values is None else np.asarray(soh_values)
    usable = usable_energy_wh(soc_pct, soh_values, temp_c, vehicle)
    rng = usable / consumption_wh_km
    return pd.DataFrame({"soh_pct": soh_values * 100, "range_km": rng,
                         "km_per_pp": np.gradient(rng, soh_values * 100)})


def temperature_sensitivity_curve(vehicle, consumption_wh_km: float, soc_pct: float,
                                  soh: float, temps=None) -> pd.DataFrame:
    """Range against ambient temperature, through the capacity derate ONLY.

    Important caveat for the UI: this shows the derate term alone. It does NOT include
    the effect of temperature on consumption itself, which in the real data is the
    larger channel -- E3 measured a 1.5 pp MAPE contribution from temperature and a
    1.7 pp contribution from the measured HVAC load it drives.
    """
    temps = np.arange(-15.0, 41.0, 1.0) if temps is None else np.asarray(temps)
    usable = usable_energy_wh(soc_pct, soh, temps, vehicle)
    return pd.DataFrame({"temp_c": temps, "range_km": usable / consumption_wh_km})
